### ISSUE TITLE
Improved documentation

### ISSUE THREAD

**Issue by murrayds** [skojaku/emlens#12]
I think there are some small updates we could implement to improve the documentation, specifically:

- [x] Use consistent parameter names, e.g., always use `emb` or always use `vec`, not both
- [x] Include references where appropriate, i.e., include the SemAxis paper as a reference to the semaxis function
- [x] Flesh out descriptions of approaches. For example, what is the radius of gyration, and what is semaxis? A little more detail should be provided
- [x] avoid the use of acronyms when not explicitly defined. For example, only use kNN if the full name, "k-nearest neighbors", has already been used in the function description
- [x] Include more description of returned types. For example, what is the type of the KNN graph object that is returned? 
- [x] Use more precise parameter terminology, for example, `locations` in `density_estimation.estimate_pdf(...)` is vague, and I think the connection of locations to density will not be immediately clear to users. Just "point" or "target" may be good enough, though I'll think on it.

**Comment by skojaku** [comment]
TODO: 
- Update the notebook. 
- The description of Semaxis is vague and some additional explanation may be needed.

**Comment by skojaku** [comment]
Done

**Comment by skojaku** [comment]
#13
